# backend: nccl
# find_unused_parameters: false
# gradient_as_bucket_view: true
# static_graph: false

distributed:
  backend: nccl
  find_unused_parameters: true
  gradient_as_bucket_view: true
  static_graph: true